### ISSUE TITLE
No known class method for selector 'keyFromPemFileWithName:'

### ISSUE THREAD

**Issue by kedington** [docusign/docusign-objc-client#19] opened 2018-08-08 23:24 UTC
After JWTs update from 3.0.0-beta.10 to 3.0.0-beta.11 we get this missing class method. It seems 'keyFromPemFileWithName' was deprecated from JWT and then removed with the newest update. 

If we add the old methods to JWTCryptoSecurity.h the project builds again 

```
//API_DEPRECATED("Use methods from JWTCryptoSecurity+Extraction.h", macos(10.4, 10.8), ios(2.0, 3.0), watchos(2.0, 3.0), tvos(9.0, 10.0))
__deprecated
@interface JWTCryptoSecurity (Pem)
+ (NSString *)certificateFromPemFileContent:(NSString *)content __deprecated;
+ (NSString *)keyFromPemFileContent:(NSString *)content __deprecated;
+ (NSArray *)itemsFromPemFileContent:(NSString *)content byRegex:(NSRegularExpression *)expression __deprecated;
+ (NSString *)certificateFromPemFileWithName:(NSString *)name __deprecated;
+ (NSString *)keyFromPemFileWithName:(NSString *)name __deprecated;
+ (NSArray *)itemsFromPemFileWithName:(NSString *)name byRegex:(NSRegularExpression *)expression __deprecated;
+ (NSString *)stringByRemovingPemHeadersFromString:(NSString *)string __deprecated;
@end
```

They suggest that the library needs to start using the methods from JWTCryptoSecurity+Extraction.h.

**Comment by Kedington** [comment] 2018-08-08 23:43
This can also be fixed by just adding pod 
`'JWT', '3.0.0-beta.10' `
to your pod file.

**Comment by LarryKlugerDS** [comment] 2020-01-08 10:01
This is essentially a duplicate of issue 21. Closed as a dup.

**Closed** 2020-01-08 10:02 UTC
Labels: duplicate
